# Generated by Django 5.2.7 on 2026-06-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address_hint',
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
