# Generated by Django 5.2.7 on 2026-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_address_hint_item_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
